export default {
  SYNTAX_ERROR: 'SYNTAX_ERROR',
  DUPLICATE_MODULE: 'DUPLICATE_MODULE',
  DUPLICATE_VARIANT: 'DUPLICATE_VARIANT',
  DUPLICATE_PROPERTY: 'DUPLICATE_PROPERTY',
  INVALID_VARIANT: 'INVALID_VARIANT',
  INVALID_PROPERTY: 'INVALID_PROPERTY',
  INVALID_VALUE: 'INVALID_VALUE',
  INVALID_FUNCTION: 'INVALID_FUNCTION',
}
